all: latex

latex:
	pdflatex presentation.tex
	pdflatex presentation.tex
	open -a Skim presentation.pdf

nonstopmode:
	pdflatex -interaction=nonstopmode presentation.tex
	pdflatex -interaction=nonstopmode presentation.tex
	open -a Skim presentation.pdf

